spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehsan_1
    username: root
    password: e19951374
#    url: jdbc:mysql://localhost:3306/ehsan
#    username: melody1
#    password: ABCMm@123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true